-- These are the table definitions for this program
-- These were autogenerated using the ERD feature of pgAdmin 4
BEGIN;


CREATE TABLE IF NOT EXISTS public.categories
(
    category_id serial NOT NULL,
    category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_id integer,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
    );

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    product_price numeric(8, 2) NOT NULL,
    product_desc text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
    );

ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;