<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Servlets About</title>
    <link href="../style/fonts.css" rel="stylesheet">
    <link href="../style/about.css" rel="stylesheet">
    <link href="../style/navbar.css" rel="stylesheet">
</head>

<body>
    <nav></nav>
    <script src="../src/setupNavBar.js"></script>

    <h1>About</h1>

    <div>
        <div class="section">
            <img data-link="https://tomcat.apache.org/" id="tomcat-logo" src="../resources/tomcat.png" alt="Tomcat Logo">
            <h3>Tomcat</h3>

            <p>
                This web application is being run by a web server known as Apache Tomcat
            </p>
            <p>
                Apache Tomcat is an HTTP webserver that works with Jakarta EE Servlets which are running this application
            </p>

            <p>
                This program is run with Tomcat 11.0.18
            </p>

        </div>

        <div class="section">
            <img data-link="https://jakarta.ee/release/11/" id="servlet-logo" src="../resources/jakarta-logo.svg" alt="Java logo">
            <h3>Jakarta Servlets</h3>

            <p>
                Apache Tomcat relies on Jakarta servlets to handle server requests. A servlet is a Java class that
                listens for server requests in a web container (Tomcat) and responds to them
            </p>
            <p>
                Servlets are the backbone of Java web applications and enable the creation of backend APIs
                which can communicate with the frontend
            </p>
            <p>
                This program is run with Jakarta EE 11
            </p>
        </div>

        <div class="section">
            <img data-link="https://www.postgresql.org/" id="postgres-logo" src="../resources/postgres-logo.png" alt="PostgreSQL Logo">
            <h3>PostgreSQL</h3>

            <p>
                PostgreSQL is used as the RDBMS for this application. The database stores all the information regarding
                the products displayed on the browse page
            </p>

            <p>
                The Java on the backend handles all the database management so the frontend never touches it.
                Instead, the frontend sends requests to the backend to fetch data from the database using proper
                CRUD operations as defined by REST principles
            </p>

            <p>
                This program uses PostgreSQL version 18.2
            </p>

            <div style="border-top: 1px solid black; padding-bottom: 0.3em;"></div>

            <h4>ERD Diagram</h4>
            <img src="../resources/ERD.png" alt="Database ERD">
            <br>

            <button id="show-schema-button">Show Schema</button>

            <div class="is-hidden" id="schema">
                <button id="schema-button">Copy Schema</button>
                <p class="is-hidden" id="copy-confirm"></p>
                <p id="schema-data">
                    -- These are the table definitions for this program
                    -- These were autogenerated using the ERD feature of pgAdmin 4
                    BEGIN;


                    CREATE TABLE IF NOT EXISTS public.categories
                    (
                    category_id serial NOT NULL,
                    category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
                    product_id integer,
                    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
                    );

                    CREATE TABLE IF NOT EXISTS public.products
                    (
                    product_id serial NOT NULL,
                    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
                    product_price numeric(8, 2) NOT NULL,
                    product_desc text COLLATE pg_catalog."default" NOT NULL,
                    CONSTRAINT products_pkey PRIMARY KEY (product_id)
                    );

                    ALTER TABLE IF EXISTS public.categories
                    ADD CONSTRAINT categories_product_id_fkey FOREIGN KEY (product_id)
                    REFERENCES public.products (product_id) MATCH SIMPLE
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION;

                    END;
                </p>
            </div>

        </div>
    </div>

    <script src="../src/about.js"></script>
</body>
</html>